name: pdf_reader
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: 0.20.2
  flutter_svg: ^2.2.0
  pull_down_button: ^0.10.2
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.0
  restart_app: ^1.3.2
  package_info_plus: ^8.3.0
  modal_bottom_sheet: ^3.0.0
  toastification: ^2.3.0
  easy_url_launcher: ^0.0.7
  shared_preferences: ^2.5.3
  rename_app: ^1.6.5
  flutter_native_splash: ^2.4.0
  get: ^4.7.2
  flutter_tts: ^4.2.3
  path_provider: ^2.0.11
  file_picker: ^10.2.1
  pdf_thumbnail: ^0.1.6+1
  flutter_fullscreen: ^1.2.0
  font_awesome_flutter: ^10.8.0
  share_plus: ^7.2.2
  image: ^4.1.7
  hive: 2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.19.0


flutter_launcher_icons:
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/logo/logo.png"  # Path to foreground image
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#FFFFFF"  # White background
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"
  android:
    generate: true
    image_path: "assets/logo/logo.png"
    color: "#FFFFFF"
    background_color: "#FFFFFF"  # White background
    icon_size: 144  # Adjust this for Android icons


flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000" # optional: dark background color
  image: assets/logo/splash.png
  image_dark: assets/logo/splash_dark.png # this is the dark mode image

  android_12:
    image: assets/logo/splash.png
    image_dark: assets/logo/splash_dark.png # dark mode image for Android 12+
    icon_background_color: "#ffffff"
    color: "#ffffff"
    color_dark: "#000000" # optional: dark background color for Android 12



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/logo/